### ISSUE TITLE
Error msg from running testrunner on dubbo:dubbo-registry-default

### ISSUE THREAD

**Issue by aksheeth-i** [idflakies/iDFlakies#43]
When running testrunner on project:  https://github.com/apache/incubator-dubbo
on SHA:                                                737f7a7ea67832d7f17517326fb2491d0a086dd7
on the module:                                    dubbo-registry/dubbo-registry-default, 

the following unresolved error message was encountered:

ERROR (WRITE_ERROR_STDOUT_THROWABLE): org.apache.dubbo:dubbo-registry-default:2.7.0-SNAPSHOT                            java.lang.Exception: Non-zero exit code
           at edu.illinois.cs.testrunner.runner.Runner.$anonfun$runWithCp$3(Runner.scala:71)                                                                                
           at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withProperties$2(TempFiles.scala:38)
           at edu.illinois.cs.testrunner.util.autoClose.$anonfun$autoCloseTry$1(autoClose.scala:7) 
           at scala.util.Try$.apply(Try.scala:209)
           at edu.illinois.cs.testrunner.util.autoClose.autoCloseTry(autoClose.scala:7) 
           at edu.illinois.cs.testrunner.util.autoClose.apply(autoClose.scala:24)
.....

**Comment by darko-marinov** [comment]
This error may be due to running with Java version greater than 8.
